### ISSUE TITLE
Value does not change when quantity value is changed.

### ISSUE THREAD

**Issue by aman1106** [KarthikeyanRanasthala/react-unit-converter#3]
Value in the third row remain same if the quantity (second row) is changed.
It should be reset to 0 (just a suggestion).

![Screenshot_2019-10-18 Unit Converter](https://user-images.githubusercontent.com/29223370/67088565-141ef280-f1c3-11e9-815b-85f2fd600392.png)

After changing centimeters to meters or any other unit, the third row value does not change, it should be reset to 0.

![Screenshot_2019-10-18 Unit Converter(1)](https://user-images.githubusercontent.com/29223370/67088718-7d9f0100-f1c3-11e9-82de-bcf147283143.png)

This does not make sense. After changing the inputs it works perfectly.

**Comment by KarthikeyanRanasthala** [comment]
@aman1106 Merged your PR.
